### ISSUE TITLE
Bot falsly tracks boosts when moves miss

### ISSUE THREAD

**Issue by EvGym** [pmariglia/showdown#104]
for example, if a pokemon nasty plotted up to 4x spa and missed overheat, it would then nasty plot again to get back up to 4x spa even though it wouldn't benefit from it

relevant testing replay:
https://replay.pokemonshowdown.com/gen8nationaldex-1535729332
turn 20

settings:
use_relative_weights = True
damage_calc_type = 'min_max_average'
search_depth = 2
dynamic_search_depth = True

I no longer have the used teams, sorry.

**Comment by hypersonicstormm** [comment]
Happened to me as well. No longer have the team/replay thought

**Comment by pmariglia** [comment]
So what you're saying is that the bot thinks its `spa` has dropped from x4 to x3 because of the miss on turn 21, and so it boosted again on turn 22.

Unfortunately the bot doesn't work that way. It doesn't assume the state based on the moves it chose. The only way for the bot to have thought its `spa` had dropped would be if the PS server sent a message indicating so, something like 

```
|-unboost|p2a: rotomheat|spa|2
```

The actual log from turn 21 is:

```
|turn|21
|
|t:|1647901897
|move|p2a: rotomheat|Overheat|p1a: kommoo|[miss]
|-miss|p2a: rotomheat|p1a: kommoo
|move|p1a: kommoo|Drain Punch|p2a: rotomheat
|-damage|p2a: rotomheat|21/100 tox
|
|-damage|p2a: rotomheat|3/100 tox|[from] psn
|upkeep
```

There is nothing in the above message to tell the bot to drop it's special attack.

What you're observing is just one of the many problems with the bot. I can't say 100% what happened without the bot's logs, but what I suspect is that on turn 22 the bot thought kommo-o outsped the bot's rotom-h (yes there is evidence that the rotom outspeeds kommo-o but the bot can't perfectly detect those things). When the bot is put into situations like this where it thinks it will certainly lose the interaction, it make really dumb decisions.

**Comment by pmariglia** [comment]
Going to close this issue as I don't see any bug here and this is really just the bot being bad.

Feel free to re-open if you feel there is an actual logic bug here that I missed.
