### ISSUE TITLE
question

### ISSUE THREAD

**Issue by SomeRandomGuy009** [pmariglia/showdown#119]
from where did u get the ou_sets.json file, can't seem to find it in smogon website

**Comment by SomeRandomGuy009** [comment]
@pmariglia

**Comment by mitchellhumphrey** [comment]
ou_sets.json is suppose to be made from data scrapped from the showdown site, it is not a file that exists on smogon servers AFAIK. There is a default ou_sets.json in the repository
https://github.com/pmariglia/showdown/blob/master/data/ou_sets.json

Also, your name of this issue is not helpful in the slightest, as it gives no information as to what your question is.

Finally there is no reason to tag the author of this repo, as either they will get notified of your post here, or they have notifications off for a reason. 

I hope this is able to answer your question.

**Comment by pmariglia** [comment]
Mitchell is correct. The data doesn't exist on smogon servers. The data comes from scraped teams from the forums as some other places.
