### ISSUE TITLE
Types from older gens not loaded

### ISSUE THREAD

**Issue by SkyePlayssGames** [pmariglia/showdown#155]
Magnemite/Magneton are still seen as steel type in gen 1 and pokemon like Mawile are seen as fairy before gen 6

**Comment by pmariglia** [comment]
gen3 is the oldest "supported" generation at the moment, although YMMV with some of the more niche interactions since I mostly focus on the current gen mechanics.

Mawile should be steel only prior to gen6 - [this mod should](https://github.com/pmariglia/showdown/blob/6d303df214f9fcac370f77fb9e4545f11911f7db/data/mods/gen5_pokedex_mods.json#L369) overwrite the pokedex.json to make the types only steel. How are you determining that Mawile is seen as fairy prior to gen6?
