### ISSUE TITLE
Docker or Python?

### ISSUE THREAD

**Issue by ghost** [pmariglia/showdown#160]
Which version is better to use?

**Comment by pmariglia** [comment]
Neither is better. It is just 2 ways of running the same code.

You should just use whichever is easier or makes more sense for you.

**Comment by Askardhiksa** [comment]
Which battle bot is the best for gen9ou? Also, I can't use nicknames, right?

**Comment by pmariglia** [comment]
Neither will be better, and that goes for any format. These are just two different ways of running the code.


Pokemon nicknames should work. Just add them in your team file as you would in any PS export file

**Comment by Askardhiksa** [comment]
Where do you get your team datasets? A lot of them look outdated, and I think I can populate them with newer ones if you could tell me how you find them.

Also, are there any settings I can turn on or change to make the bot stronger, even if it takes more time to calculate?

**Comment by Askardhiksa** [comment]
And the bot keeps only using Terrastalize on the last Pokemon.

**Comment by Askardhiksa** [comment]
For example, I experimented by changing to this - https://www.smogon.com/stats/2023-06/chaos/gen9ou-1825.json

**Comment by Askardhiksa** [comment]
For example, I experimented by changing to this - https://www.smogon.com/stats/2023-06/chaos/gen9ou-1825.json.

**Comment by pmariglia** [comment]
>Where do you get your team datasets? 
>For example, I experimented by changing to this - https://www.smogon.com/stats/2023-06/chaos/gen9ou-1825.json.

The team datasets are scraped from Smogon forum pages where people share their teams. I have stopped doing that as it requires compute resources to constantly look for new teams on the forums.

If you follow the format of that file, you can manually overwrite it however you see fit, and then the bot will use that file when inferring spreads/moves/etc.

>And the bot keeps only using Terrastalize on the last Pokemon.

By design. Knowing when to terastallize is really complicated. The bot is only able to update it's representation of the battle after something terastallizes.

**Comment by Askardhiksa** [comment]
Are there any settings I can turn on to improve the bot?
