### ISSUE TITLE
Bot too fast

### ISSUE THREAD

**Issue by link-discord** [pmariglia/showdown#200]
When I run the bot on my server the bot calculates the next move very quickly but sends the next move so fast that pokemon showdown thinks it is still the same turn, causing showdown to reject the move and the bot to break.

The server is running an `AMD Ryzen 9 7950X3D (12) @ 4.191GHz`

I used the `nash_equilibrium` battle bot.

**Comment by pmariglia** [comment]
I think its unlikely that the bot is too fast. I've been privately running tens of thousands of fast (100ms decision time) battles and have had no issue.

What I have seen is that sometimes the bot gets confused about what turn it is and tries to send the same move twice in a row before realizing there have been more messages from P.S. and then deciding for the correct turn. Never have I seen this result in the bot breaking or getting stuck (which is why I've never really looked deeper into it).

To help me debug here, could you provide me some of:
- the bots logs leading up to the crash (maybe 3-4 turns prior)
- your env configuration (omit credentials)

**Comment by link-discord** [comment]
I cant seem to be able to reproduce the bug and neither do I have the logs anymore of when the bug occured, so I will just close this issue for now, if I happen to get it again I will just reopen this issue or something.
