### ISSUE TITLE
Nash Equilibrium.

### ISSUE THREAD

**Issue by ididoopsy123** [pmariglia/showdown#201]
I am currently working on a project involving Nash Equilibrium, and I've encountered some issues when running the script. The script is located in the directory "showdown>showdown>battle_bot>nash_equilibrium>main.py". However, I'm receiving errors such as "Could not find pandas" or "No module named nashpy." Additionally, there are yellow underlines appearing in the script file.

Could you please provide guidance on how to resolve these issues? It seems that some modules might be missing or not correctly installed, but I'm not sure how to proceed. Any help would be greatly appreciated!

Thank you for your support.

Best regards,
Ally.

![Screenshot 2024-08-13 165542](https://github.com/user-attachments/assets/a3e04991-a546-4dff-a78f-b012f078d213)

**Comment by pmariglia** [comment]
[from the README:](https://github.com/pmariglia/showdown?tab=readme-ov-file#nash-equilibrium-experimental)

`The Nash Equilibrium is calculated using command-line tools provided by the [Gambit](http://www.gambit-project.org/) project. This decision method should only be used when running with Docker and will fail otherwise.`

You're getting those errors because you don't have pandas or nashpy installed. Those come from a [separate requirements file](https://github.com/pmariglia/showdown/blob/master/requirements-docker.txt) that is meant to be used with Docker. Even if you installed these you'd likely error when trying to calculate the nash-equilibrium unless you have the gambit binaries installed on your system and have their locations in your PATH

As for your yellow lines, you are probably not configuring your editor properly for this project. I cannot help you there.
