### ISSUE TITLE
Bot not utilizing Dynamax

### ISSUE THREAD

**Issue by egriesheim** [pmariglia/showdown#23]
Playing gen8battlestadiumsingles on the default bot and through 10 games, Dynamax has not been used.

**Comment by pmariglia** [comment]
Yes, this is intentional.

Knowing when it is good or bad to Dynamax is not simple given the way the bots in the repo are implemented. I also don't see myself spending much time on this given that it is likely to be banned in OU in the next week or two.

I may re-visit this if Dynamax continues to exist in other popular formats, but it's just not a priority for me right now.

**Comment by pmariglia** [comment]
As a compromise, I've edited the decision logic to always Dynamax on the last Pokemon if Dynamax is available. This does **not** include understanding of what MaxMoves actually do.

See 05495f73d5
