### ISSUE TITLE
Get link of saved battle

### ISSUE THREAD

**Issue by lawrenceztang** [pmariglia/showdown#37]
The link of a saved battle is not displayed, and it is difficult to get the link because when spectators are disabled, which is the default, the replay link has a code of random characters in it. I'm not experienced with the web socket stuff and I don't want to get into it.

**Comment by pmariglia** [comment]
The easiest way to get a saved replay for a match played by the bot would be to go to https://replay.pokemonshowdown.com and search for the username that the bot ran as.

**Comment by pmariglia** [comment]
I see, that's a bit annoying. Especially with the increased amount of private battles lately due to the check-box for invite-only.

It could probably be coded in to wait for the server to respond with a replay link, and then log it.

However, there is a workaround:

1. Log into the account that the bot played as on https://play.pokemonshowdown.com
2. Navigate to https://replay.pokemonshowdown.com (your session is preserved)
3. Search for your own username

The search results should have a `Public` and `Private` tab, and you can see your replays.

**Comment by lawrenceztang** [comment]
Alright, thanks!
