### ISSUE TITLE
hackmons cup not working?

### ISSUE THREAD

**Issue by IndigoGems** [pmariglia/showdown#72]
bot is idle and wont make moves

**Comment by pmariglia** [comment]
Thnx for the report!

While the format technically could work with a small change. It would break in other places because of issue #3.

Hackmons Cup allows multiple pokemon of the same species on one team. If the bot gets a team with two of the same pokemon it will crash.

For now I'm just going to say that this isn't a supported format.

**Comment by IndigoGems** [comment]
Ah I see. I'll be closing this issue then.
