### ISSUE TITLE
Error when running python run.py

### ISSUE THREAD

**Issue by shadesofsoft** [pmariglia/showdown#73]
Traceback (most recent call last):
  File "C:\Users\who\Downloads\showdown-master\showdown-master\run.py", line 111, in <module>
    asyncio.get_event_loop().run_until_complete(showdown())
  File "C:\Users\who\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\who\Downloads\showdown-master\showdown-master\run.py", line 70, in showdown
    parse_configs()
  File "C:\Users\who\Downloads\showdown-master\showdown-master\run.py", line 36, in parse_configs
    config.username = env("PS_USERNAME")
  File "C:\Users\whoAppData\Local\Programs\Python\Python39\lib\site-packages\environs\__init__.py", line 80, in method
    raise EnvError('Environment variable "{}" not set'.format(proxied_key or parsed_key))
environs.EnvError: Environment variable "PS_USERNAME" not set

whats wrong :(

also, how do i create an .env file? do i right click and create text document and name it .env?

**Comment by shadesofsoft** [comment]
also, how do i create an `.env` file? do i right click and create text document and name it .env?

**Comment by shadesofsoft** [comment]
is there any fix to this?

**Comment by merkrafter** [comment]
The problem is that the username for the bot could not be read from the .env file (because you don't have one, I suppose). To create it, just create a text document as you said, and paste the minimal example from the README.md into it via a note pad, for instance.

**Comment by shadesofsoft** [comment]
hmm i did exactly what u did and the exact same error has come up. by order. i cloned the repo into the directory i wanted with gitbash. then i installed requirements.txt. then i created the .env file in the directory. i rightclicked the repo folder and opened gitbash in that directory. then i ran python run.py. it still didnt work.

i added u on discord btw im azrael. im hoping to resolve this :(

**Comment by pmariglia** [comment]
Hi!

The bot needs certain environment variables set in order to run. You can either set them yourself, or the bot will read environment variables from a file named `.env` in the root of the repository just as the README mentions.

I've accepted your Discord request if you'd like to chat further there.

**Comment by pmariglia** [comment]
After talking privately it turns out the file `.env` didn't exist for @shadesofsoft 

@shadesofsoft is using windows, which automatically makes any new file a `.txt` file. The extension doesn't exist in the filename when looking through the file explorer so it looked like the file existed but it did not.
